### ISSUE TITLE
I can't found env-openshift

### ISSUE THREAD

**Issue by Scisci75** [jenkins-x/cloud-environments#124]
sorry, but i can't found env-openshift. has been it removed?
Thanks
Mirko

**Comment by phu-mai** [comment]
I got the same issue =))

**Comment by daveconde** [comment]
I hit this also, using --provider=minishift got me going again in a testing cluster. @jstrachan would you accept a PR to add these back in?

**Comment by jstrachan** [comment]
@daveconde PRs most welcome - not sure how it got removed
