### ISSUE TITLE
make the use of the domain easier to override?

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/cloud-environments#20]
the exposecontroller settings and domain are encoded in a secret for thunder which makes it hard to use locally or to change the domain etc.

I wonder if we can make it easier to change those? 

As a work around I hacked the `secrets.yaml.dec` locally then added these new targets in the Makefile...
```
local-install:
	helm install jenkins-x/$(CHART) --name $(RELEASE) -f ./myvalues.yaml -f ./secrets.yaml.dec --version $(CHART_VERSION) $(ARGS)

local-upgrade:
	helm upgrade $(RELEASE) jenkins-x/$(CHART) -f myvalues.yaml -f secrets.yaml.dec --version $(CHART_VERSION) $(ARGS)    
```

wonder if there's a cleaner way?

**Comment by jstrachan** [comment]
maybe we just add those extra targets to the thunder Makefile?

**Comment by rawlingsj** [comment]
yeah sounds good

**Comment by rawlingsj** [comment]
Not an issue anymore
